### ISSUE TITLE
Getting Https error while adding an app

### ISSUE THREAD

**Issue by MoonWalker440** [Sinneida/glassdown#78]
![Screenshot_20240630_142225.jpg](https://github.com/Sinneida/glassdown/assets/155570047/eba8ed47-2e5a-4ec7-9151-34771d626d3b)

Hey there, I am getting this error every time when I am adding any app

**Comment by Sinneida** [comment]
This is probably due to the fact, that you've been using app "too much" and that fired up the APKMirror Cloudflare protection. Try to switch to WiFi if you're on mobile data (or the other way around if you're using WiFi while doing requests) and app should be running. This Cloudflare protection will reset after a while, 30 minutes or so. You can also try to open APKMirror page in the browser and tick the checkbox "I'm not a robot" from Cloudflare if it pops out.

**Comment by MoonWalker440** [comment]
Ok. got it

**Comment by Sinneida** [comment]
Kind of fixed in #87, the app will show more helpful message when this happens
