### ISSUE TITLE
Firefox Beta for Testers:`No versions found` error

### ISSUE THREAD

**Issue by arghya339** [Sinneida/glassdown#83]
https://www.apkmirror.com/apk/mozilla/firefox-beta/

**Comment by Sinneida** [comment]
Well, it's because I'm filtering versions by looking for "beta" or "alpha" strings in the app name. Since all the versions in the link you've provided have "Beta" in name, the list is empty. When you're in the Versions view, tap Quick Settings button and uncheck "Exclude unstable" and then pull to refresh the versions list.

**Comment by Sinneida** [comment]
Since app search will be changed to use APP search filter from APKMirror query parameter, this can be actually fixed.

**Comment by Sinneida** [comment]
Fixed in #87, searching for Firefox will show this app
